### ISSUE TITLE
Sub Package Support

### ISSUE THREAD

**Issue by adarzulfu** [gmatyszczak/screen-generator-plugin#11]
Really greate work! Thank you

I was wondering if it is possible to auto create sub package under selected package for MVVM. For example I have 3 main package "data - domain - presentation" under my main module named "sample". So If i select the main module package (com.sample) to create templated files it should create these files under appropriate package;

```
-com
  -sample
    -data
         -source
            -other_feature_1
            -other_feature_2
            -other_feature_3
            -new_feature
                *NewFeatureDataSource
    -domain
        -interactor
           -other_feature_1
           -other_feature_2
           -other_feature_3
           -new_feature
             *NewFeatureInteractor
    -presentation
          -other_feature_1
          -other_feature_2
          -other_feature_3
          -new_feature
            *NewFeatureFragment
            *NewFeatureViewModel
```

Basically, my question is that the generator currently create all files to the selected package. How to create new package and move some generated file to it (fragment, viewmodel etc.)

**Comment by gmatyszczak** [comment]
Hi @adarzulfu, for now it's not possible. But I will mark it as enhancement to add in the future :)

**Comment by gmatyszczak** [comment]
It took a while but requested feature was officially added to v1.2.0 :)

There are couple more features like multiple categories, custom variables for each category, related android component, subdirectory and source set for each screen element.

**Comment by JuanchiFraga** [comment]
@gmatyszczak  how can i use this feature on 1.2.0? I trying something like this but the subpackage would not created. See what happend on the second image.
![image](https://user-images.githubusercontent.com/29152510/147693809-501697a9-9bec-4634-a679-15d493e400ab.png)
![image](https://user-images.githubusercontent.com/29152510/147693922-e5a29fe3-017d-42ae-a8c2-bbb879e64eaf.png)

**Comment by gmatyszczak** [comment]
@JuanchiFraga Use `/` in subdirectory, e.g. `presentation/viewmodel`

**Comment by JuanchiFraga** [comment]
@gmatyszczak I still can't get it to work :(
![image](https://user-images.githubusercontent.com/29152510/147782714-163fa589-bc67-42b7-a63c-96000dabe5de.png)
![image](https://user-images.githubusercontent.com/29152510/147782748-efb2437d-4ab5-4fbc-8f24-927f0eb6804e.png)

**Comment by JuanchiFraga** [comment]
I would like to do something like that
![image](https://user-images.githubusercontent.com/29152510/147782871-4bf42daf-2432-4799-ac5a-fd8c1fcb6e43.png)
