### ISSUE TITLE
Why add groups?

### ISSUE THREAD

**Issue by BitMobix** [gmatyszczak/screen-generator-plugin#12]
Cool idea), especially for Android Studio 4.1 and higher.

![image](https://user-images.githubusercontent.com/67513829/92325748-adfac280-f055-11ea-9acc-e3d7d1d55fe9.png)

But why can't I create groups?

Let's say I want to create not only MVP, but MVVM, Also an Adapter.

There is no choice at all. add please

**Comment by gmatyszczak** [comment]
Hi @BitMobix,
I'm not sure if I understand correctly, isn't it the same enhancement as here #7 ?

**Comment by gmatyszczak** [comment]
It took a while but requested feature was officially added to v1.2.0 :)

There are couple more features like custom variables for each category, related android component, subdirectory and source set for each screen element.
