### ISSUE TITLE
Error with Android Studio 4.1

### ISSUE THREAD

**Issue by MikyJoo** [gmatyszczak/screen-generator-plugin#13]
Hi.

Thank you for useful plugin.
It helps many thing to me.

But it does not work after updating 4.1 today.
I think it cannot load module list.

Please, check and fix it.

**Comment by gmatyszczak** [comment]
Hi, thanks for reporting the issue!

I will try to get back to it later today :)

**Comment by gmatyszczak** [comment]
@MikyJoo Please update to version 1.1.1, issue is fixed :)

**Comment by MikyJoo** [comment]
@gmatyszczak 
Wow. It works well.
Thank you very much.
