### ISSUE TITLE
Can't recognize package for module

### ISSUE THREAD

**Issue by Pantkowsky** [gmatyszczak/screen-generator-plugin#17]
I have stumbled upon an issue when auto-generating code using this plugin.

Everything works as intended, until there is a wild keyword in the package: `features`. We have a multi-module project in our team, and keep all features as separate modules, within a `features` directory. The exemplary project structure looks like:
```
- app
- domain
- features
    - login
    - chat
    - ...
```
We can use the plugin to auto-generate the code from `app` and `domain`, however when trying to do it from `login` or `chat`, the default package is not automatically recognized.

The above results in no files being generated, except for one: `layout`. This one however is placed in `/main/java/layout/` instead of `main/res/layout`.

Interestingly enough, when changing the directory name from `features` to anything else **that does not include** `features` in its name, the package gets recognized, and code generation works. As an example, renaming to `shared`, `testing`, `something`, etc works, however renaming that directory to `app-features` **does not**. 

Would love to get any help here, as renaming that directory is a possible workaround, however I would love to avoid doing that.

**Comment by gmatyszczak** [comment]
Thanks for detailed description!

Please check version 1.2.1 of the plugin, the issue should be fixed there
