### ISSUE TITLE
Android Studio Studio Dolphin | 2021.3.1 Setting Infinte Loading

### ISSUE THREAD

**Issue by james602152002** [gmatyszczak/screen-generator-plugin#28]
Build #AI-213.7172.25.2113.9014738, built on September 1, 2022

File->Setting->Screen Generator Plugin
always infinte loading, I cannot edit my settingsT_T

**Comment by ederdoski** [comment]
same issue

**Comment by gmatyszczak** [comment]
Fixed in [v1.2.2](https://github.com/gmatyszczak/screen-generator-plugin/releases/tag/v1.2.2)
