### ISSUE TITLE
Files created in wrong locations

### ISSUE THREAD

**Issue by alextabusca** [gmatyszczak/screen-generator-plugin#3]
Hi! First of all I really like your work as it can prove very useful when you have to create lots of fragments in your app(as I do right now).

But I found that even though I specify the full package name, the files are created in the wrong locations:

- the layout files are created in the app/src/debug/res/layout as opposed to app/src/main/res/layout
- the Kotlin files are created in the app/src/main/assets folder where it also creates a package with the given name(the entered package path)

Could you have a look at the source of the issue? Thanks a lot :)

**Comment by gmatyszczak** [comment]
Glad to hear you like it! I will take a look at these issues :)

**Comment by gmatyszczak** [comment]
@alextabusca You can update to version 1.0.2 and check if it works now :)

**Comment by alextabusca** [comment]
It's working perfectly 👌 
Thanks a lot!
