### ISSUE TITLE
Plugin puts files into main > baselineProfile folder

### ISSUE THREAD

**Issue by denisStuzo** [gmatyszczak/screen-generator-plugin#34]
Hi!
When I have baselineProfile folder in the project, the plugin considers it as a folder to put classes of my screen. 
What can I do with it? Maybe some settings?
Thanks 

<img width="550" alt="Screenshot 2024-10-08 at 15 40 03" src="https://github.com/user-attachments/assets/bd54bb44-cb81-4d04-a08c-d59255b7168b">

**Comment by gmatyszczak** [comment]
@denisStuzo Please try out newly released version 1.2.4, it should be fixed
