### ISSUE TITLE
Feature Request: Share Templates

### ISSUE THREAD

**Issue by MohamedMedhat-Robusta** [gmatyszczak/screen-generator-plugin#35]
In our company, we all follow the same MVI guidelines.  

I have created a category like this  

![image](https://github.com/user-attachments/assets/18b85b72-37e3-4b10-a217-db63de688eb2)  

And I want to share it with other teammates. How can I do this?  

And how can I import a template from someone else?

**Comment by gmatyszczak** [comment]
@MohamedMedhat-Robusta Thanks for trying out my plugin! All configuration is saved in `.idea/screenGeneratorConfiguration.xml` file in your project, so you can just make sure that it's not filtered out by `.gitignore`, and your teammates will be able to use it when pulling the code from repository. Plugin will pick up this configuration automatically.

**Comment by MohamedMedhat-Robusta** [comment]
@gmatyszczak Awesome! Didn't know about that.  
That is exactly what I want. Thanks a lot.
