### ISSUE TITLE
Can't Undo/Redo

### ISSUE THREAD

**Issue by DjakaTechnology** [gmatyszczak/screen-generator-plugin#9]
Hello, First of all good work and thanks for making it open source it really helped me. 

Recently I tried to modified your plugin to fulfill my team needs and stumble across this issue. It seems I can't undo my action after generating a screen. This give me quite a hassle since my module is quite big and I have to scroll through it to delete it one by one.

It seems to wrap WriteActionDispatcherImpl.dispatch with `WriteCommandAction.runWriteCommandAction` instead of `ApplicationManager.getApplication().runWriteAction` solved the issue.

I can open a PR if you need a hand on this, feel free to tell me anytime

And again, thank you for creating this plugin and the medium article I really appreciate it 👍

**Comment by gmatyszczak** [comment]
Hi, thanks for feedback!

If you have already a working solution then please go ahead and create a PR :)

**Comment by DjakaTechnology** [comment]
I've opened a PR for this. Thank you :D

**Comment by gmatyszczak** [comment]
Plugin update is live now, you can check version 1.1.0 :)
